import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blue Tians",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <div className="relative min-h-screen flex flex-col">
          <div className="absolute inset-0">
            <div className="absolute inset-0 bg-amber-900/30 z-10"></div>
            <div className="absolute inset-0 bg-[url('/bg.jpg')] bg-cover bg-center bg-fixed bg-no-repeat opacity-90 blur-xs"></div>
          </div>

          <div className="relative flex flex-col flex-1 z-20">
            <Header />
            <main className="flex-1 container mx-auto px-2 sm:px-4 py-4 sm:py-6 my-auto">
              <div className="flex items-center justify-center">

              {children}
              </div>
            </main>

            <footer className="py-3 sm:py-4 px-3 sm:px-6 text-center md:text-left text-amber-100/80 text-sm backdrop-blur-sm bg-amber-950/30">
              <div className="container mx-auto">
                <div className="flex flex-col md:flex-row md:justify-between items-center gap-2">
                  <p>
                    Indian Classical Music • Explore the beauty of ragas and
                    taals
                  </p>
                  <div className="text-xs opacity-80 mt-1 md:mt-0">
                    © {new Date().getFullYear()} Blue Titans
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
